name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up python
      uses: actions/setup-python@main
      with: 
         python-version: '3.10'

    - name: Install
      shell: bash
      run: |
        pip install --upgrade pip
        pip install -r docs/requirements.txt

    - name: Build HTML
      run: |
        cd docs/source/
        sphinx-build -D language=en -b html ./ _build/html



    - name: Deploy to GitHub pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
         folder: docs/source/_build/html
