name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: doc/build/html/
        
    - name: Deploy to GitHub pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
           folder: doc/build/html/
